### ISSUE TITLE
reshape layer seems not work correctly

### ISSUE THREAD

**Issue by Pinnh** [XiaoMi/mace#352]
### System information
- **OS Platform and Distribution  Linux Ubuntu 16.04 
- **NDK version 16b 
- **GCC version 5.4.0 
- **MACE version master
- **Python version 2.7 
- **Bazel version 0.13.1

### Describe the problem
when set reshape params as follow:
layer {
  name: "mbox_priorbox_reshape"
  type: "Reshape"
  bottom: "mbox_priorbox"
  top: "mbox_priorbox_reshape"
  reshape_param {
    shape {
      dim: 0
      dim: 2
      dim: 8000
      dim: 1
    }
   }
}
run command : python tools/converter.py convert --config=ssd.yml
I get : 
mbox_priorbox (Concat, index:41): [[1L, 2L, 8000L]]
**mbox_priorbox_reshape** (Reshape, index:42): [[1L, 8000L, 1L, 2L]]

expect: **mbox_priorbox_reshape** (Reshape, index:42): [[1L, 2L, 8000L, 1L]]

**Comment by lydoc** [comment]
Could you use the latest master branch and try again? We have fixed a bug just now.

**Comment by Pinnh** [comment]
use latest master version mace , issue still happened as same as before 

also a new issue(or is a feature ? I don't know) happens
when reshape from 3 dims to 4 dims(add a dim at last) ,run converter will crash

Transform model to one that can better run on device
Traceback (most recent call last):
  File "/home/di/test/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 363, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/di/test/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 194, in main
    output_graph_def = converter.run()
  File "/home/di/test/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 224, in run
    shape_inferer.run()
  File "/home/di/test/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/shape_inference.py", line 72, in run
    self._op_shape_inference[op.type](op)
  File "/home/di/test/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/shape_inference.py", line 267, in infer_shape_reshape
    output_shape[i] = self._output_shape_cache[op.input[0]][i]
IndexError: list index out of range
Traceback (most recent call last):
  File "tools/converter.py", line 1300, in <module>
    flags.func(flags)
  File "tools/converter.py", line 774, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 704, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/di/test/mace/tools/sh_commands.py", line 532, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

(python tools/converter.py convert --config=ssd.yml)

**Comment by lydoc** [comment]
Is it convenient for you to provide your model and yml files?

**Comment by Pinnh** [comment]
sure, by the way,  this model will crash when running in cell phone(gpu mode), I don't konw what happens.
the issue is no detail information just crash with libc    : Fatal signal 6 (SIGABRT), code -6

site: https://pan.baidu.com/s/1K2SJDu0T7E4_2ZZmclZiig 
extract code: phsi

**Comment by lydoc** [comment]
We fixed some bugs just now, could you try the latest master branch? By the way, for the previous issue: 
> mbox_priorbox (Concat, index:41): [[1L, 2L, 8000L]]
**mbox_priorbox_reshape** (Reshape, index:42): [[1L, 8000L, 1L, 2L]]

This is because mace convert caffe NCHW format to NHWC.

**Comment by Pinnh** [comment]
Um, I changed reshape params to [1,1,8000,2], the output shape of **mbox_priorbox_reshape** is same as  [[1L, 2L, 8000L, 1L]] , so it seems reshape layer works correctly, but the application still crash with Fatal signal 6 (SIGABRT) ,  or I change output shape [1,2000] to [1,2000,1,1] it will cash as follows:

02-18 06:36:01.917 13738 13738 F MACE    : mace.cc:645 Check failed: output_size <= output->second.impl_->buffer_size Output size exceeds buffer size: shape[1, 546748024545] vs buffer size 2000
02-18 06:36:01.917 13738 13738 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 13738 (com.rk.test)

other models(non-ssd model) are all no crash issue.

**Comment by lydoc** [comment]
Oh, forgot to tell you, I think the bottom of mbox_priorbox_reshape layer has the shape [1, 2, 4000], so are you supposed to reshape mbox_priorbox to [1,1,4000,2] instead of [1,1,8000,2]?

**Comment by Pinnh** [comment]
Yes, the shape of mbox_priorbox has been changed, I am not ware of this problem. I change the code as your mention,and the problem is resolved. thanks~
